### ISSUE TITLE
"Sign_in" url no longer works

### ISSUE THREAD

**Issue by Denubis** [tbmihailov/overleaf-backup-tool#6]
When running this, 

```
Traceback (most recent call last):                                                                                                                                                            │····  File "overleaf_backup.py", line 48, in <module>                                                                                                                                             │····    overleaf_client.login_with_user_and_pass(username, password)                                                                                                                              │····  File "/data/overleaf-backup-tool/clients/OverleafClient.py", line 122, in login_with_user_and_pass                                                                                          │····    raise Exception(err_msg)                                                                                                                                                                  │····Exception: Status code 404 when loading https://www.overleaf.com//users/sign_in. Can not continue...   
```
it looks like overleaf has shifted enough that this script no longer works. Do you have any plans to maintain it?

**Comment by alpha-oliveira** [comment]
At least, he could answer.
